### ISSUE TITLE
Error: Invalid listen argument: [object Object] on NodeJS 7.0.0

### ISSUE THREAD

**Issue by gx0r** [wzrdtales/socket-io-sticky-session#22]
Started getting the following error with NodeJS 7.0.0:

``` js

Error: Invalid listen argument: [object Object]
    at Server.listen (net.js:1384:13)
    at Server.listen (/home/u/app/node_modules/socketio-sticky-session/lib/sticky-session.js:227:22)
    at Object.<anonymous> (/home/u/app/src/server/server.js:77:8)
    at Module._compile (module.js:573:32)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Function.Module.runMain (module.js:607:10)
    at /usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:159:24
    at Object.<anonymous> (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:160:7)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

```

**Comment by vizo** [comment]
https://github.com/wzrdtales/socket-io-sticky-session/pull/23
